# Generated by Django 5.0.2 on 2024-03-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionApp', '0001_initial'),
        ('mainApp', '0017_alter_product_brand'),
        ('userApp', '0002_delete_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('user', 'product')},
        ),
    ]
