# Generated by Django 5.0.2 on 2024-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_image_product_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_sub',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
