# Generated by Django 5.0.2 on 2024-02-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_productproperty_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='context',
            field=models.CharField(max_length=1024),
        ),
    ]
