# Generated by Django 5.0.2 on 2024-03-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_productproperty_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
