# Generated by Django 5.0.2 on 2024-03-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_order_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
    ]
